### ISSUE TITLE
implement new fetures

### ISSUE THREAD

**Issue by khushirathore11** [imharshtiwari/Hacktober-fest-2024#24]
I hope this message finds you well.

I am writing to formally request the assignment of an issue related to the implementation of a new feature for the project as part of Hacktoberfest 2024. I believe that this feature would significantly enhance the functionality and user experience of the application.

Proposed Feature: [Briefly describe the feature you intend to implement, including its purpose and potential benefits.]

I am eager to contribute to this project and look forward to your feedback on my proposal. Thank you for considering my request.
Best Regards.

**Comment by imharshtiwari** [comment]
Hi [khushirathore11],

Thank you for reaching out and for your enthusiasm about contributing to our project during Hacktoberfest 2024!

I appreciate your proposal for the new feature. Please provide a brief description of the feature you intend to implement, including its purpose and potential benefits, so we can better evaluate how it aligns with our project goals.

Looking forward to hearing more about your ideas!
