### ISSUE TITLE
To implement z-index property in css

### ISSUE THREAD

**Issue by Ayesha19297** [imharshtiwari/Hacktober-fest-2024#28]

**Comment by PiyushhBansal** [comment]
assign this project to me under label of hacktoberfest

**Comment by imharshtiwari** [comment]
Hai [PiyushhBansal]
You have rasie PR for getting succesfull acceptance of PR for Hacktober Dashboard
you can cheack out readme.md file

**Comment by Ayesha19297** [comment]
Hii Harsh tiwari,
I noticed that this issue was closed and marked as completed, but I
couldn't find any related pull request. Could you clarify, shall I submit
the PR for the same.

--
Thanks & Regards,
Ayesha
Rising software developer
